/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ConnectFourInterface extends utils.Interface {
  functions: {
    "challenge(address)": FunctionFragment;
    "didPlayerWin(uint8,uint8,uint8,uint8)": FunctionFragment;
    "getGame(uint256)": FunctionFragment;
    "getGameBoard(uint256)": FunctionFragment;
    "makeMove(uint8,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "challenge"
      | "didPlayerWin"
      | "getGame"
      | "getGameBoard"
      | "makeMove"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "challenge",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "didPlayerWin",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameBoard",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "makeMove",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "challenge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "didPlayerWin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGameBoard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "makeMove", data: BytesLike): Result;

  events: {
    "GameCreated(uint256,address,address)": EventFragment;
    "GameFinished(address,uint256)": EventFragment;
    "TurnTaken(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GameCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GameFinished"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TurnTaken"): EventFragment;
}

export interface GameCreatedEventObject {
  gameId: BigNumber;
  teamOne: string;
  teamTwo: string;
}
export type GameCreatedEvent = TypedEvent<
  [BigNumber, string, string],
  GameCreatedEventObject
>;

export type GameCreatedEventFilter = TypedEventFilter<GameCreatedEvent>;

export interface GameFinishedEventObject {
  winner: string;
  gameId: BigNumber;
}
export type GameFinishedEvent = TypedEvent<
  [string, BigNumber],
  GameFinishedEventObject
>;

export type GameFinishedEventFilter = TypedEventFilter<GameFinishedEvent>;

export interface TurnTakenEventObject {
  team: string;
  column: BigNumber;
}
export type TurnTakenEvent = TypedEvent<
  [string, BigNumber],
  TurnTakenEventObject
>;

export type TurnTakenEventFilter = TypedEventFilter<TurnTakenEvent>;

export interface ConnectFour extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConnectFourInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    challenge(
      opponent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    didPlayerWin(
      _gameId: PromiseOrValue<BigNumberish>,
      column: PromiseOrValue<BigNumberish>,
      row: PromiseOrValue<BigNumberish>,
      teamNum: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getGame(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, string] & {
        teamOne: string;
        teamTwo: string;
        turn: number;
        winner: string;
      }
    >;

    getGameBoard(
      _gameId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number[][]]>;

    makeMove(
      _gameId: PromiseOrValue<BigNumberish>,
      column: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  challenge(
    opponent: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  didPlayerWin(
    _gameId: PromiseOrValue<BigNumberish>,
    column: PromiseOrValue<BigNumberish>,
    row: PromiseOrValue<BigNumberish>,
    teamNum: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getGame(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, number, string] & {
      teamOne: string;
      teamTwo: string;
      turn: number;
      winner: string;
    }
  >;

  getGameBoard(
    _gameId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number[][]>;

  makeMove(
    _gameId: PromiseOrValue<BigNumberish>,
    column: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    challenge(
      opponent: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    didPlayerWin(
      _gameId: PromiseOrValue<BigNumberish>,
      column: PromiseOrValue<BigNumberish>,
      row: PromiseOrValue<BigNumberish>,
      teamNum: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getGame(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, number, string] & {
        teamOne: string;
        teamTwo: string;
        turn: number;
        winner: string;
      }
    >;

    getGameBoard(
      _gameId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number[][]>;

    makeMove(
      _gameId: PromiseOrValue<BigNumberish>,
      column: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "GameCreated(uint256,address,address)"(
      gameId?: null,
      teamOne?: null,
      teamTwo?: null
    ): GameCreatedEventFilter;
    GameCreated(
      gameId?: null,
      teamOne?: null,
      teamTwo?: null
    ): GameCreatedEventFilter;

    "GameFinished(address,uint256)"(
      winner?: null,
      gameId?: null
    ): GameFinishedEventFilter;
    GameFinished(winner?: null, gameId?: null): GameFinishedEventFilter;

    "TurnTaken(address,uint256)"(
      team?: null,
      column?: null
    ): TurnTakenEventFilter;
    TurnTaken(team?: null, column?: null): TurnTakenEventFilter;
  };

  estimateGas: {
    challenge(
      opponent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    didPlayerWin(
      _gameId: PromiseOrValue<BigNumberish>,
      column: PromiseOrValue<BigNumberish>,
      row: PromiseOrValue<BigNumberish>,
      teamNum: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGame(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGameBoard(
      _gameId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    makeMove(
      _gameId: PromiseOrValue<BigNumberish>,
      column: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    challenge(
      opponent: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    didPlayerWin(
      _gameId: PromiseOrValue<BigNumberish>,
      column: PromiseOrValue<BigNumberish>,
      row: PromiseOrValue<BigNumberish>,
      teamNum: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGame(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGameBoard(
      _gameId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    makeMove(
      _gameId: PromiseOrValue<BigNumberish>,
      column: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
