/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Battleship } from "./Battleship";
export type { BattleshipFactory } from "./BattleshipFactory";
export type { BattleshipImpl } from "./BattleshipImpl";
export * as factories from "./factories";
export { Battleship__factory } from "./factories/Battleship__factory";
export { BattleshipFactory__factory } from "./factories/BattleshipFactory__factory";
export { BattleshipImpl__factory } from "./factories/BattleshipImpl__factory";
