name: Publish NPM Package
on: 
  release:
    types: [created]

jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest
    needs: contract-tests 
    steps:
      - name: Compile Contracts
        run: pnpm run compile
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.CONTRACTS_NPM_TOKEN }}
