name: Publish NPM Package
on: 
  release:
    types: [created]

jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest
    needs: contract-tests 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm ci
      - name: Compile Contracts
        run: pnpm run compile
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.CONTRACTS_NPM_TOKEN }}
